version: '3.4'

services:

  teacher.api:
    image: ${DOCKER_REGISTRY-}teacherapi
    build:
      context: .
      dockerfile: TeacherService/Dockerfile

  servicesgateway:
    image: ${DOCKER_REGISTRY-}servicegateway
    build:
      context: .
      dockerfile: ServicesGateway/Dockerfile
