using Flaminco.CommitResult;
using IdentityDomain.Features.ExternalIdentityProvider.DTO.Remove.Command;

namespace IdentityDomain.Features.ExternalIdentityProvider.CQRS.Command;
public record RemoveExternalIdentityProviderCommand(RemoveExternalIdentityProviderRequest RemoveExternalIdentityProviderRequest) : IRequest<ICommitResult>;